# Generated by Django 5.2.1 on 2025-05-24 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Κωδικός')),
                ('first_name', models.CharField(max_length=100, verbose_name='Όνομα')),
                ('last_name', models.CharField(max_length=100, verbose_name='Επώνυμο')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Επωνυμία Εταιρείας')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλέφωνο')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Διεύθυνση')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Πόλη')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ταχ. Κώδικας')),
                ('vat_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Α.Φ.Μ.')),
                ('doy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Δ.Ο.Υ.')),
                ('shipping_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Διεύθυνση Αποστολής')),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Πόλη Αποστολής')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ταχ. Κώδικας Αποστολής')),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα Επικοινωνίας')),
                ('contact_person_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλ. Επικοινωνίας')),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Επικοινωνίας')),
                ('payment_method', models.CharField(choices=[('cash', 'Μετρητά'), ('bank_transfer', 'Κατάθεση σε Τράπεζα'), ('credit_card', 'Πιστωτική/Χρεωστική Κάρτα'), ('cheque', 'Επιταγή'), ('other', 'Άλλο')], default='bank_transfer', max_length=50, verbose_name='Τρόπος Πληρωμής')),
                ('payment_terms', models.CharField(choices=[('due_on_receipt', 'Άμεση Εξόφληση'), ('net_15', 'Επί Πιστώσει 15 Ημερών'), ('net_30', 'Επί Πιστώσει 30 Ημερών'), ('net_60', 'Επί Πιστώσει 60 Ημερών'), ('eom', 'Τέλος Μηνός'), ('other', 'Άλλο')], default='net_30', max_length=50, verbose_name='Όροι Πληρωμής')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Πιστωτικό Όριο (€)')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Υπόλοιπο (€)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Σχόλια')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση')),
            ],
            options={
                'verbose_name': 'Πελάτης',
                'verbose_name_plural': 'Πελάτες',
                'ordering': ['company_name', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα Προϊόντος')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Κωδικός Προϊόντος')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Τιμή Πώλησης (€)')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Τιμή Κόστους (€)')),
                ('unit_of_measurement', models.CharField(choices=[('pcs', 'Τεμάχια'), ('kg', 'Κιλά'), ('meter', 'Μέτρα'), ('liter', 'Λίτρα'), ('box', 'Κιβώτια'), ('other', 'Άλλο')], default='pcs', max_length=50, verbose_name='Μονάδα Μέτρησης')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ποσότητα στο Απόθεμα')),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ελάχιστο Όριο Αποθέματος')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση')),
            ],
            options={
                'verbose_name': 'Προϊόν',
                'verbose_name_plural': 'Προϊόντα',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Αριθμός Τιμολογίου')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Συνολικό Ποσό (€)')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.customer', verbose_name='Πελάτης')),
            ],
            options={
                'verbose_name': 'Τιμολόγιο',
                'verbose_name_plural': 'Τιμολόγια',
                'ordering': ['-date', 'customer'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Παραγγελίας')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Παράδοσης')),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμής'), ('processing', 'Σε Επεξεργασία / Προς Αποστολή'), ('completed', 'Ολοκληρωμένη'), ('cancelled', 'Ακυρωμένη')], default='pending', max_length=50, verbose_name='Κατάσταση')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Συνολικό Ποσό (€)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Σχόλια Παραγγελίας')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Αριθμός Παραγγελίας')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.customer', verbose_name='Πελάτης')),
            ],
            options={
                'verbose_name': 'Παραγγελία',
                'verbose_name_plural': 'Παραγγελίες',
                'ordering': ['-order_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Ποσότητα')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Τιμή Μονάδας (€)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Συνολική Τιμή Είδους (€)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Σχόλια Είδους')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Παραγγελία')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Είδος Παραγγελίας',
                'verbose_name_plural': 'Είδη Παραγγελίας',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Περιγραφή Είδους')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Ποσότητα')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Τιμή Μονάδας (€)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice', verbose_name='Τιμολόγιο')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Είδος Τιμολογίου',
                'verbose_name_plural': 'Είδη Τιμολογίου',
            },
        ),
    ]
