# Generated by Django 5.2.1 on 2025-05-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Αριθμός Παρτίδας'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Λήξης'),
        ),
    ]
