# Generated by Django 5.2.1 on 2025-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_batch_number_product_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True, verbose_name='Κανονικοποιημένο Όνομα'),
        ),
    ]
