# Generated by Django 5.2.1 on 2025-05-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_name_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True, verbose_name='Επωνυμία Κανονικοποιημένη'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True, verbose_name='Όνομα Κανονικοποιημένο'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True, verbose_name='Επώνυμο Κανονικοποιημένο'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηнία Δημιουργίας'),
        ),
    ]
