# Generated by Django 5.2.1 on 2025-05-29 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_company_name_normalized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσότητα Εισαγωγής')),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερομηνία & Ώρα Παραλαβής')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις Παραλαβής')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Προϊόν')),
                ('user_who_recorded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης Καταχώρησης')),
            ],
            options={
                'verbose_name': 'Παραλαβή Αποθέματος',
                'verbose_name_plural': 'Παραλαβές Αποθεμάτων',
                'ordering': ['-date_received'],
            },
        ),
    ]
