# Generated by Django 5.2.1 on 2025-05-30 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_alter_order_created_at_stockreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία & Ώρα')),
                ('action_type', models.CharField(choices=[('CREATE', 'Δημιουργία'), ('UPDATE', 'Ενημέρωση'), ('DELETE', 'Διαγραφή'), ('LOGIN', 'Είσοδος Χρήστη'), ('LOGOUT', 'Έξοδος Χρήστη'), ('STATUS_CHANGE', 'Αλλαγή Κατάστασης')], max_length=20, verbose_name='Τύπος Ενέργειας')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Αντικειμένου')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Αναπαράσταση Αντικειμένου')),
                ('details', models.TextField(blank=True, verbose_name='Λεπτομέρειες')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Τύπος Αντικειμένου')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Καταγραφή Ενέργειας',
                'verbose_name_plural': 'Καταγραφές Ενεργειών',
                'ordering': ['-action_time'],
            },
        ),
    ]
