# Generated by Django 5.2.1 on 2025-06-02 19:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Πληρωμής/Καταχώρησης')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό Πληρωμής (€)')),
                ('payment_method', models.CharField(choices=[('cash', 'Μετρητά'), ('bank_transfer', 'Κατάθεση σε Τράπεζα'), ('credit_card', 'Πιστωτική/Χρεωστική Κάρτα'), ('cheque', 'Επιταγή'), ('online', 'Online Πληρωμή'), ('other', 'Άλλο')], default='cash', max_length=50, verbose_name='Τρόπος Πληρωμής')),
                ('value_date', models.DateField(blank=True, help_text='Για επιταγές ή άλλες πληρωμές με μελλοντική ημερομηνία ισχύος.', null=True, verbose_name='Ημερομηνία Λήξης/Value Date')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Αριθμός Αναφοράς/Παραστατικού')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας Εγγραφής')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση Εγγραφής')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.customer', verbose_name='Πελάτης')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.order', verbose_name='Συσχετιζόμενη Παραγγελία')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Καταχωρήθηκε από')),
            ],
            options={
                'verbose_name': 'Πληρωμή',
                'verbose_name_plural': 'Πληρωμές',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
