# Generated by Django 5.2.1 on 2025-06-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-receipt_number'], 'verbose_name': 'Πληρωμή', 'verbose_name_plural': 'Πληρωμές'},
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Αρ. Απόδειξης Συστήματος'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Π.χ. αριθμός χειρόγραφης απόδειξης, ID τραπεζικής συναλλαγής, αριθμός επιταγής', max_length=100, null=True, verbose_name='Εξωτερικός Αρ. Αναφοράς/Παραστατικού'),
        ),
    ]
