# Generated by Django 5.2.1 on 2025-06-03 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_payment_options_payment_receipt_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Λόγος Ακύρωσης'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Ακύρωσης'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_payments', to=settings.AUTH_USER_MODEL, verbose_name='Ακυρώθηκε από'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('active', 'Ενεργή'), ('cancelled', 'Ακυρωμένη')], default='active', max_length=20, verbose_name='Κατάσταση Πληρωμής'),
        ),
    ]
