# Generated by Django 5.2.1 on 2025-06-06 21:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment_cancellation_reason_payment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Αριθμός Τιμολογίου')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Έκδοσης')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Λήξης')),
                ('status', models.CharField(choices=[('draft', 'Πρόχειρο'), ('issued', 'Εκδόθηκε'), ('paid', 'Εξοφλήθηκε'), ('cancelled', 'Ακυρώθηκε')], default='draft', max_length=20, verbose_name='Κατάσταση')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Υποσύνολο (€)')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=24.0, max_digits=5, verbose_name='Ποσοστό ΦΠΑ (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ποσό ΦΠΑ (€)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Συνολικό Ποσό (€)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις Τιμολογίου')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.customer', verbose_name='Πελάτης')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='core.order', verbose_name='Σχετική Παραγγελία')),
            ],
            options={
                'verbose_name': 'Τιμολόγιο',
                'verbose_name_plural': 'Τιμολόγια',
                'ordering': ['-issue_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Περιγραφή')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσότητα')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Τιμή Μονάδας (προ ΦΠΑ)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Συνολική Αξία (προ ΦΠΑ)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice', verbose_name='Τιμολόγιο')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Είδος Τιμολογίου',
                'verbose_name_plural': 'Είδη Τιμολογίου',
            },
        ),
    ]
