# Generated by Django 5.2.1 on 2025-06-08 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='payments', to='core.invoice', verbose_name='Συσχετιζόμενα Τιμολόγια'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Συνολική Αξία (προ ΦΠΑ)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.order', verbose_name='Συσχετιζόμενη Παραγγελία (παλαιό)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Εξωτερικός Αρ. Αναφοράς/Παραστατικού'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Λήξης/Value Date'),
        ),
    ]
