# Generated by Django 5.2.1 on 2025-06-08 13:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_payment_invoices_alter_invoiceitem_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='vat_percentage',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ποσό ΦΠΑ (€)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('24.00'), max_digits=5, verbose_name='Ποσοστό ΦΠΑ (%)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Συνολικό Ποσό ΦΠΑ (€)'),
        ),
    ]
