# Generated by Django 5.2.1 on 2025-06-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_invoice_vat_percentage_invoiceitem_vat_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Εξοφλημένο Ποσό (€)'),
        ),
    ]
