# Generated by Django 5.2.1 on 2025-06-08 22:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_orderitem_vat_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('24.00'), max_digits=5, verbose_name='ΦΠΑ (%)'),
        ),
    ]
