# Generated by Django 5.2.1 on 2025-06-09 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_vat_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Ποσό Έκπτωσης (€)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ποσοστό Έκπτωσης (%)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_gift',
            field=models.BooleanField(default=False, verbose_name='Δώρο'),
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλέφωνο')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ποσοστό Προμήθειας (%)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Λογαριασμός Χρήστη')),
            ],
            options={
                'verbose_name': 'Αντιπρόσωπος/Πωλητής',
                'verbose_name_plural': 'Αντιπρόσωποι/Πωλητές',
                'ordering': ['user__username'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.salesrepresentative', verbose_name='Υπεύθυνος Πωλητής/Αντιπρόσωπος'),
        ),
    ]
