# Generated by Django 5.2.1 on 2025-06-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_invoice_discount_amount_invoice_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Διεύθυνση Αποστολής'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Πόλη Αποστολής'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Όνομα Παραλήπτη'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Τ.Κ. Αποστολής'),
        ),
    ]
