# Generated by Django 5.2.1 on 2025-06-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_shipping_address_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Έκπτωση Είδους (%)'),
        ),
    ]
