# Generated by Django 5.2.1 on 2025-06-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_orderitem_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Συνολική Τιμή Είδους (με ΦΠΑ)'),
        ),
    ]
