# Generated by Django 5.2.1 on 2025-06-11 16:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Έκπτωση Είδους (%)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_gift',
            field=models.BooleanField(default=False, verbose_name='Δώρο'),
        ),
    ]
