# Generated by Django 5.2.1 on 2025-06-12 19:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_invoiceitem_discount_percentage_invoiceitem_is_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='rep_type',
            field=models.CharField(choices=[('SALES', 'Εσωτερικός Πωλητής'), ('AGENT', 'Εξωτερικός Αντιπρόσωπος')], default='SALES', max_length=10, verbose_name='Τύπος'),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Υπολογισμένο Ποσό Προμήθειας (€)')),
                ('calculation_date', models.DateField(auto_now_add=True, verbose_name='Ημερομηνία Υπολογισμού')),
                ('status', models.CharField(choices=[('UNPAID', 'Ανεξόφλητη'), ('PAID', 'Εξοφλημένη')], default='UNPAID', max_length=10, verbose_name='Κατάσταση')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πληρωμής')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice', verbose_name='Σχετικό Τιμολόγιο')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salesrepresentative', verbose_name='Πωλητής/Αντιπρόσωπος')),
            ],
            options={
                'verbose_name': 'Προμήθεια',
                'verbose_name_plural': 'Προμήθειες',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Αρ. Πιστωτικού')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Έκδοσης')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Αιτία Έκδοσης (π.χ. Επιστροφή προϊόντων)')),
                ('status', models.CharField(choices=[('DRAFT', 'Πρόχειρο'), ('ISSUED', 'Εκδόθηκε'), ('APPLIED', 'Εφαρμόστηκε')], default='DRAFT', max_length=10, verbose_name='Κατάσταση')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Υποσύνολο (€)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Συνολικό Ποσό ΦΠΑ (€)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Συνολικό Ποσό (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='core.customer', verbose_name='Πελάτης')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='core.invoice', verbose_name='Αρχικό Τιμολόγιο')),
            ],
            options={
                'verbose_name': 'Πιστωτικό Τιμολόγιο',
                'verbose_name_plural': 'Πιστωτικά Τιμολόγια',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Περιγραφή')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσότητα Επιστροφής')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Τιμή Μονάδας (προ ΦΠΑ)')),
                ('vat_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ποσοστό ΦΠΑ (%)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Συνολική Αξία Γραμμής (προ ΦΠΑ)')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό ΦΠΑ Γραμμής (€)')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.creditnote', verbose_name='Πιστωτικό Τιμολόγιο')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Προϊόν')),
            ],
            options={
                'verbose_name': 'Είδος Πιστωτικού Τιμολογίου',
                'verbose_name_plural': 'Είδη Πιστωτικών Τιμολογίων',
            },
        ),
    ]
