# Generated by Django 5.2.1 on 2025-06-13 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_salesrepresentative_rep_type_commission_creditnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Πρόχειρο'), ('issued', 'Εκδόθηκε'), ('paid', 'Εξοφλήθηκε'), ('cancelled', 'Ακυρώθηκε'), ('credited', 'Πιστώθηκε')], default='draft', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0dcaf0', max_length=7, verbose_name='Βασικό Χρώμα Θέματος (π.χ. #0dcaf0)')),
                ('background_color', models.CharField(default='#fffaf5', max_length=7, verbose_name='Χρώμα Φόντου Σελίδας (π.χ. #fffaf5)')),
                ('sidebar_color', models.CharField(default='#eef8ff', max_length=7, verbose_name='Χρώμα Πλευρικού Μενού (π.χ. #eef8ff)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Προφίλ Χρήστη',
                'verbose_name_plural': 'Προφίλ Χρηστών',
            },
        ),
    ]
