# Generated by Django 5.2.1 on 2025-06-14 14:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_invoice_status_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Αρ. Απόδειξης')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερομηνία & Ώρα Έκδοσης')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Υποσύνολο (€)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Συνολικό Ποσό ΦΠΑ (€)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Συνολικό Ποσό (€)')),
                ('status', models.CharField(choices=[('ISSUED', 'Εκδόθηκε'), ('CANCELLED', 'Ακυρώθηκε')], default='ISSUED', max_length=10, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_receipts', to='core.customer', verbose_name='Πελάτης')),
            ],
            options={
                'verbose_name': 'Απόδειξη Λιανικής',
                'verbose_name_plural': 'Αποδείξεις Λιανικής',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='RetailReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Περιγραφή')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσότητα')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Τιμή Μονάδας (με ΦΠΑ)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Έκπτωση Είδους (%)')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Τελική Αξία Γραμμής (€)')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Προϊόν')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.retailreceipt', verbose_name='Απόδειξη Λιανικής')),
            ],
            options={
                'verbose_name': 'Είδος Απόδειξης Λιανικής',
                'verbose_name_plural': 'Είδη Απόδειξης Λιανικής',
            },
        ),
    ]
