# Generated by Django 5.2.1 on 2025-06-14 22:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_retailreceipt_retailreceiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailreceiptitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Καθαρή Αξία Γραμμής (€)'),
        ),
        migrations.AddField(
            model_name='retailreceiptitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ποσό ΦΠΑ Γραμμής (€)'),
        ),
    ]
