# Generated by Django 5.2.1 on 2025-06-15 13:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_retailreceiptitem_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailreceiptitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Τιμή Μονάδας (προ ΦΠΑ)'),
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_number', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Αρ. Δελτίου Αποστολής')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Έκδοσης')),
                ('status', models.CharField(choices=[('PREPARING', 'Προετοιμάζεται'), ('SHIPPED', 'Απεστάλη'), ('DELIVERED', 'Παραδόθηκε'), ('CANCELLED', 'Ακυρώθηκε')], default='PREPARING', max_length=20, verbose_name='Κατάσταση')),
                ('shipping_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Όνομα Παραλήπτη')),
                ('shipping_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Διεύθυνση Αποστολής')),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Πόλη Αποστολής')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Τ.Κ. Αποστολής')),
                ('carrier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Μεταφορέας')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Αριθμός Αποστολής (Tracking)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις Δελτίου')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='core.customer', verbose_name='Πελάτης')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_note', to='core.order', verbose_name='Σχετική Παραγγελία')),
            ],
            options={
                'verbose_name': 'Δελτίο Αποστολής',
                'verbose_name_plural': 'Δελτία Αποστολής',
                'ordering': ['-issue_date', '-delivery_note_number'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Περιγραφή')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσότητα')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.deliverynote', verbose_name='Δελτίο Αποστολής')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Προϊόν')),
            ],
        ),
    ]
