# Generated by Django 5.2.1 on 2025-06-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_retailreceiptitem_unit_price_deliverynote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='mark',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='ΜΑΡΚ myDATA'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='purpose',
            field=models.CharField(choices=[('SALE', 'Πώληση'), ('SAMPLE', 'Δειγματισμός'), ('REPAIR', 'Προς Επισκευή'), ('RETURN', 'Επιστροφή'), ('INTERNAL', 'Εσωτερική Διακίνηση'), ('OTHER', 'Άλλο')], default='SALE', max_length=20, verbose_name='Σκοπός Διακίνησης'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='qr_code_url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name=' σύνδεσμος QR Code'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='shipping_vat_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ΑΦΜ Παραλήπτη'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mark',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='ΜΑΡΚ myDATA'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='qr_code_url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name=' σύνδεσμος QR Code'),
        ),
    ]
