# Generated by Django 5.2.1 on 2025-06-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_deliverynote_mark_deliverynote_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Αριθμός Κυκλοφορίας Οχήματος'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='core.customer', verbose_name='Πελάτης Χρέωσης'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='core.order', verbose_name='Σχετική Παραγγελία'),
        ),
    ]
