# Generated by Django 5.2.1 on 2025-06-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_deliverynote_license_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='carrier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Μεταφορέας'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Αριθμός Κυκλοφορίας Οχήματος'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purpose',
            field=models.CharField(blank=True, choices=[('SALE', 'Πώληση'), ('SAMPLE', 'Δειγματισμός'), ('REPAIR', 'Προς Επισκευή'), ('RETURN', 'Επιστροφή'), ('INTERNAL', 'Εσωτερική Διακίνηση'), ('OTHER', 'Άλλο')], default='SALE', max_length=20, null=True, verbose_name='Σκοπός Διακίνησης'),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Μεταφορέας'),
        ),
        migrations.AddField(
            model_name='order',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Αριθμός Κυκλοφορίας Οχήματος'),
        ),
        migrations.AddField(
            model_name='order',
            name='purpose',
            field=models.CharField(blank=True, choices=[('SALE', 'Πώληση'), ('SAMPLE', 'Δειγματισμός'), ('REPAIR', 'Προς Επισκευή'), ('RETURN', 'Επιστροφή'), ('INTERNAL', 'Εσωτερική Διακίνηση'), ('OTHER', 'Άλλο')], default='SALE', max_length=20, null=True, verbose_name='Σκοπός Διακίνησης'),
        ),
    ]
