# Generated by Django 5.2.1 on 2025-06-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_invoice_carrier_invoice_license_plate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sales_rep',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_branch',
            field=models.BooleanField(default=False, verbose_name='Είναι Υποκατάστημα;'),
        ),
        migrations.AddField(
            model_name='customer',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Επιλέξτε αν αυτός ο πελάτης είναι υποκατάστημα ενός άλλου.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='core.customer', verbose_name='Κεντρικό Κατάστημα'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Κωδικός'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('parent', 'code'), name='unique_branch_code_for_parent'),
        ),
    ]
