# Generated by Django 5.2.1 on 2025-06-19 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_customer_sales_rep_customer_is_branch_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_branch_code_for_parent',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_name_normalized',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name_normalized',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name_normalized',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shipping_postal_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='can_be_invoiced',
            field=models.BooleanField(default=True, help_text='Απο-επιλέξτε το για υποκαταστήματα που δέχονται μόνο Δελτία Αποστολής.', verbose_name='Δυνατότητα Τιμολόγησης'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='core.deliverynote', verbose_name='Σχετικό Δελτίο Αποστολής'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Διεύθυνση Αποστολής'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Πόλη Αποστολής'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Όνομα Παραλήπτη (Αποστολή)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Τ.Κ. Αποστολής'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_vat_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ΑΦΜ Παραλήπτη (Αποστολή)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Κωδικός'),
        ),
    ]
