# Generated by Django 5.2.1 on 2025-06-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_customer_unique_branch_code_for_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100),
        ),
    ]
