# Generated by Django 5.2.1 on 2025-06-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_customer_company_name_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='UID myDATA'),
        ),
    ]
