# Generated by Django 5.2.1 on 2025-06-22 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_invoice_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.salesrepresentative', verbose_name='Υπεύθυνος Πωλητής/Αντιπρόσωπος'),
        ),
    ]
