# Generated by Django 5.2.1 on 2025-06-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_customer_sales_rep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Επωνυμία Προμηθευτή')),
                ('name_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Όνομα Επικοινωνίας')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Διεύθυνση')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Πόλη')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ταχ. Κώδικας')),
                ('vat_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Α.Φ.Μ.')),
                ('doy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Δ.Ο.Υ.')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Σχόλια')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση')),
            ],
            options={
                'verbose_name': 'Προμηθευτής',
                'verbose_name_plural': 'Προμηθευτές',
                'ordering': ['name'],
            },
        ),
    ]
