# Generated by Django 5.2.1 on 2025-06-23 19:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Αρ. Εντολής Αγοράς')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία Παραγγελίας')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Αναμενόμενη Ημερ. Παράδοσης')),
                ('status', models.CharField(choices=[('DRAFT', 'Πρόχειρη'), ('ORDERED', 'Παραγγέλθηκε'), ('PARTIALLY_RECEIVED', 'Μερικώς Παραληφθείσα'), ('COMPLETED', 'Ολοκληρωμένη'), ('CANCELLED', 'Ακυρωμένη')], default='DRAFT', max_length=20, verbose_name='Κατάσταση')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Συνολικό Ποσό (€)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.supplier', verbose_name='Προμηθευτής')),
            ],
            options={
                'verbose_name': 'Εντολή Αγοράς',
                'verbose_name_plural': 'Εντολές Αγοράς',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσότητα')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Τιμή Κόστους Μονάδας (€)')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Συνολικό Κόστος Γραμμής (€)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Προϊόν')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaseorder', verbose_name='Εντολή Αγοράς')),
            ],
        ),
    ]
