# Generated by Django 5.2.1 on 2025-06-24 05:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ποσότητα που Παραλήφθηκε'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.purchaseorderitem', verbose_name='Γραμμή Εντολής Αγοράς'),
        ),
    ]
