# Generated by Django 5.2.1 on 2025-06-25 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0037_purchaseorderitem_quantity_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='Αρχείο')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Περιγραφή')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία & Ώρα Ανεβάσματος')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Επισυναπτόμενο Αρχείο',
                'verbose_name_plural': 'Επισυναπτόμενα Αρχεία',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
